import Head from 'next/head'
import styles from '../styles/Home.module.css'
import prisma from '@/backend/libs/prisma/prisma_client'
import Fixture from '@/backend/core/domains/Fixture'
interface PageProps {
  fixtures: Fixture[]
}
export default function Home({ fixtures }: PageProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          Hello
          {JSON.stringify(fixtures)}
        </div>
      </main>
    </>
  )
}


export const getServerSideProps = async () => {
  const fixtures = await prisma.fixture.findMany({
    include: {
      homeTeam: true,
      awayTeam: true,
    }
  })
  console.log({ fixtures })
  return {
    props: {
      fixtures: JSON.parse(JSON.stringify(fixtures)) 
    },
  }
}